/**
 * packages/shared/src/types/domain.ts
 *
 * Canonical domain model for the Meridian investor platform.
 *
 * These types are the single source of truth for:
 *  – the PostgreSQL schema shape (snake_case columns map 1:1)
 *  – the backend repository & service return types
 *  – the API response JSON structure
 *  – the frontend form value shape (via InvestorOnboardingInput)
 *
 * No HTTP, framework, or database imports live here.
 */

/** Lifecycle states an investor account can occupy. */
export type InvestorStatus = "pending_kyc" | "active" | "suspended" | "closed";

/**
 * Full persisted investor record — mirrors every column of the
 * `investors` PostgreSQL table exactly.
 *
 * Temporal fields are ISO-8601 strings so the type works identically
 * in both Node.js (where pg returns Date objects cast to TEXT via ::TEXT)
 * and the browser (where JSON deserialisation produces strings).
 */
export interface InvestorRecord {
  /** UUIDv4 primary key generated by PostgreSQL's gen_random_uuid(). */
  id: string;
  /** Investor's full legal name — max 200 characters. */
  full_name: string;
  /** Normalised to lowercase by the Zod transform before persistence. */
  email: string;
  /** ISO-8601 date-only string: YYYY-MM-DD. */
  date_of_birth: string;
  /** ISO 3166-1 alpha-2 code, uppercase. E.g. "GB", "US". */
  country: string;
  /** Current KYC / account lifecycle status. */
  status: InvestorStatus;
  /** UTC ISO-8601 datetime of initial record creation. */
  created_at: string;
  /** UTC ISO-8601 datetime of the most recent update. */
  updated_at: string;
}

/**
 * The validated, application-level input required to create a new investor.
 * The id, status, created_at, and updated_at columns are generated
 * server-side and are deliberately absent here.
 */
export type CreateInvestorInput = Pick<
  InvestorRecord,
  "full_name" | "email" | "date_of_birth" | "country"
>;
